FROM python:3.10-slim

# Install manually all the missing libraries
RUN apt-get update && apt-get install -y \
    libasound2 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    fonts-liberation \
    libnss3 \
    lsb-release \
    xdg-utils \
    wget \
    xvfb \
    gpg \
    curl \
    unzip \
    libvulkan1 \
    && rm -rf /var/lib/apt/lists/*

# Install Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /usr/share/keyrings/chrome.gpg
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
#RUN apt-get update && apt-get install -y google-chrome-stable=132.0.6834.83-1 && rm -rf /var/lib/apt/lists/*
RUN wget -O /tmp/google-chrome.deb \
    https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_133.0.6943.53-1_amd64.deb && \
    apt install -y /tmp/google-chrome.deb && \
    apt-mark hold google-chrome-stable && \
    rm -rf /tmp/google-chrome.deb /var/lib/apt/lists/*

RUN google-chrome --version

# Set up display
ENV DISPLAY=:99
RUN printf '#!/bin/bash\nXvfb :99 -screen 0 1280x1024x24 &\nexec "$@"\n' > /entrypoint.sh \
    && chmod +x /entrypoint.sh

# Install Python dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

ENV PYTHONUNBUFFERED True
ENV APP_HOME /app
ENV PORT 5000

WORKDIR $APP_HOME
COPY . ./

ENTRYPOINT ["python", "general_robot.py"]
#CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 --log-level debug --access-logfile - app:app